"""create tracking domain tables

Revision ID: 60bb5a7d5861
Revises: 215c39d7dba5
Create Date: 2026-08-26 01:54:17.042559

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '60bb5a7d5861'
down_revision: str | Sequence[str] | None = '215c39d7dba5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_categories_key'), 'tracking_categories', ['key'], unique=True)
    op.create_table('baselines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mood', sa.SmallInteger(), nullable=False),
    sa.Column('anxiety', sa.SmallInteger(), nullable=False),
    sa.Column('energy', sa.SmallInteger(), nullable=False),
    sa.Column('sleep_quality', sa.Enum('poor', 'fair', 'good', 'great', name='sleep_quality'), nullable=False),
    sa.Column('meds_adherence_2wk', sa.Enum('consistent', 'missed_1_2', 'missed_several', 'inconsistent', name='meds_adherence'), nullable=False),
    sa.Column('career_example', sa.Text(), nullable=False),
    sa.Column('structure_example', sa.Text(), nullable=False),
    sa.Column('life_example', sa.Text(), nullable=False),
    sa.Column('what_works', sa.Text(), nullable=False),
    sa.Column('non_negotiables', sa.Text(), nullable=True),
    sa.Column('cadence', sa.Enum('daily', 'every_other_day', 'weekly', name='baseline_cadence'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baselines_user_id'), 'baselines', ['user_id'], unique=True)
    op.create_table('checkin_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.Column('anxiety', sa.Integer(), nullable=False),
    sa.Column('meds', sa.Boolean(), nullable=False),
    sa.Column('sleep', sa.Text(), nullable=False),
    sa.Column('last_homework_status', sa.Enum('done', 'partial', 'missed', 'n_a', name='homework_status'), nullable=False),
    sa.Column('last_homework_note', sa.Text(), nullable=False),
    sa.Column('gap_reflection', sa.Text(), nullable=False),
    sa.Column('what_worked', sa.Text(), nullable=False),
    sa.Column('what_didnt', sa.Text(), nullable=False),
    sa.Column('tool_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pattern_flagged', sa.Text(), nullable=False),
    sa.Column('roadmap_phase_name', sa.Text(), nullable=False),
    sa.Column('next_homework', sa.Text(), nullable=False),
    sa.Column('next_homework_due', sa.Date(), nullable=True),
    sa.Column('streak_at_logging', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkin_logs_user_id'), 'checkin_logs', ['user_id'], unique=False)
    op.create_index('ix_checkin_logs_user_id_date', 'checkin_logs', ['user_id', 'date'], unique=False)
    op.create_table('exposure_hierarchy_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('initial_suds', sa.Integer(), nullable=False),
    sa.Column('current_suds', sa.Integer(), nullable=True),
    sa.Column('climbed', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exposure_hierarchy_items_user_id'), 'exposure_hierarchy_items', ['user_id'], unique=False)
    op.create_table('roadmap_phase_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('from_phase', sa.Integer(), nullable=False),
    sa.Column('to_phase', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('earned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_phase_history_user_id'), 'roadmap_phase_history', ['user_id'], unique=False)
    op.create_table('tracking_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('cadence', sa.Enum('daily', 'weekly', 'monthly', name='tracking_cadence'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tracking_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', 'cadence', 'period_start', name='uq_tracking_entry_period')
    )
    op.create_index(op.f('ix_tracking_entries_category_id'), 'tracking_entries', ['category_id'], unique=False)
    op.create_index(op.f('ix_tracking_entries_user_id'), 'tracking_entries', ['user_id'], unique=False)
    op.create_table('user_roadmap_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phase_index', sa.Integer(), nullable=False),
    sa.Column('intro_acknowledged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roadmap_state_user_id'), 'user_roadmap_state', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roadmap_state_user_id'), table_name='user_roadmap_state')
    op.drop_table('user_roadmap_state')
    op.drop_index(op.f('ix_tracking_entries_user_id'), table_name='tracking_entries')
    op.drop_index(op.f('ix_tracking_entries_category_id'), table_name='tracking_entries')
    op.drop_table('tracking_entries')
    op.drop_index(op.f('ix_roadmap_phase_history_user_id'), table_name='roadmap_phase_history')
    op.drop_table('roadmap_phase_history')
    op.drop_index(op.f('ix_exposure_hierarchy_items_user_id'), table_name='exposure_hierarchy_items')
    op.drop_table('exposure_hierarchy_items')
    op.drop_index('ix_checkin_logs_user_id_date', table_name='checkin_logs')
    op.drop_index(op.f('ix_checkin_logs_user_id'), table_name='checkin_logs')
    op.drop_table('checkin_logs')
    op.drop_index(op.f('ix_baselines_user_id'), table_name='baselines')
    op.drop_table('baselines')
    op.drop_index(op.f('ix_tracking_categories_key'), table_name='tracking_categories')
    op.drop_table('tracking_categories')
    # ### end Alembic commands ###
    # Autogenerate doesn't drop the Postgres ENUM types backing these columns
    # on its own (only DROP TABLE); do it explicitly so downgrade -> upgrade
    # is actually idempotent (same gotcha as 215c39d7dba5).
    sa.Enum(name='tracking_cadence').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='homework_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='baseline_cadence').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='meds_adherence').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sleep_quality').drop(op.get_bind(), checkfirst=True)
